### ISSUE TITLE
Junkertown (Patch 1.15.x) voice lines missing

### ISSUE THREAD

**Issue by pasky** [Overwatch-Item-Tracker/sounds#1]
Voice lines from patch 1.15.x (and possibly 1.14.x) are still missing. Do you have some instructions for extracting them so that I could make a PR ? Or we'd be happy to help with annotating the lines.

**Comment by JarrodS846** [comment]
Yeah I have the sounds it's just I use to be able to run my tools have have it automagically generate the data. I can manually extract them however I don't have an easy way to manually edit the data as it was designed to be generated automatically.

**Comment by Js41637** [comment]
Yeah I have the sounds it's just I use to be able to run my tools have have it automagically generate the data. I can manually extract them however I don't have an easy way to manually edit the data as it was designed to be generated automatically.

**Comment by Js41637** [comment]
I'll probably make some sort of interface to make it so I can edit the data a bit easier. The app already supports naming files directly on the page as you listen however it's only enabled when running locally or when dev mode is enabled. I might add an option to enable them on the site however it is all locally edited and you just download the new JSON data which is what I do.

**Comment by Js41637** [comment]
I added all the new sounds which includes all the mercy and junkrat ones. Also a couple lines in Mei, Zarya and Hanzo as well as new Athena sounds. Also the new sounds for "The Queen" on Junkertown

**Comment by pasky** [comment]
Appreciate your regular updates! We'd still be happy to contribute given instructions on how to extract the sound files on input.

**Comment by Js41637** [comment]
I use and work on [OWLib](https://github.com/overtools/OWLib) and make use of CASCExplorer. I use to extract all this data and sort it automatically but there have been a lot of changes recently and most of it is done painfully and manually. I need to rewrite all of my scripts and drastically change how I organised the data as there are some big issues with it currently (dupes, conflicting ids).

**Comment by pasky** [comment]
Oh I see - wish I had enough time to help with that but all I can do is root for you! (And help spread the word about this great project.) Good luck getting it working again!
